local input_data_file = os.getenv("INPUT_DATA_FILE")
local ollama_host = os.getenv("OLLAMA_HOST")
local file = io.open(input_data_file, "r")
local input_data = file:read("*all")
file:close()
-- args = decode(input_data)
print(ollama_host)
print(input_data)
print(args)